rails g model address_units
rails g model address_unit_descriptions
rails g model address_unit_acrons
rails g model address_labels
rails g model address_unit_labels
rails g model address_unit_images
rails g model address_unit_activities
rails g model address_activity_types
rails g model address_enterprises
rails g model address_enterprise_companies
rails g model address_enterprise_company_users
rails g model address_enterprise_indication_allotments
rails g model address_enterprise_indication_allotment_values
rails g model address_enterprise_indication_action_types
rails g model address_enterprise_indications
rails g model address_enterprise_indication_actions
rails g model address_enterprise_indication_action_documents

